using VinoDellaCasa.Domain.Entities;
using VinoDellaCasa.Domain.Enums;
using VinoDellaCasa.Domain.Maturity;

namespace VinoDellaCasa.Domain.Seed;

/// <summary>
/// Anonymous demo cellar (53 bottles: Bordeaux sample + Suisse / Provence / Champagne). Public-safe extract — no personal profile,
/// no critic prose. ReadyToDrink via <see cref="MaturityRules"/> for asOfYear.
/// </summary>
public static class DemoSample50SeedData
{
    public static readonly DateTimeOffset SeedTimestamp =
        new(2026, 9, 18, 14, 0, 0, TimeSpan.Zero);

    public static IReadOnlyList<Bottle> CreateSeeds(int asOfYear = 2026)
    {
        var specs = new (Guid Id, string Name, string Producer, string Region, string Country,
            Color Color, string? Varietal, int Vintage, int Quantity, string Bin)[]
        {
            (Guid.Parse("191f47c6-a82d-5018-863b-958c1edda37c"),
                "Domaine de la Solitude", "Domaine de la Solitude", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Petit Verdot", 2021, 2, "A1"),
            (Guid.Parse("093e4448-1a50-582b-95ca-128ba0af0481"),
                "Domaine de Chevalier", "Domaine de Chevalier", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc", 2016, 1, "B2"),
            (Guid.Parse("85831549-2c4e-5750-8534-2593264b96f2"),
                "L'Esprit de Chevalier", "Domaine de Chevalier", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Petit Verdot", 2018, 2, "C3"),
            (Guid.Parse("0428ab4f-a78e-5fae-ba3e-fd4462318c3d"),
                "Château Pape Clément", "Château Pape Clément", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot", 2021, 1, "D4"),
            (Guid.Parse("45a66abd-bc73-54b0-93fe-ecedd6950f27"),
                "Château Haut-Brion", "Château Haut-Brion", "Pessac-Léognan", "France",
                Color.Red, "Merlot, Cabernet Sauvignon, Cabernet Franc", 2017, 1, "E5"),
            (Guid.Parse("d86e818f-3ff4-5baf-820a-26626975ab29"),
                "Château Haut-Bailly", "Château Haut-Bailly", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2014, 1, "A6"),
            (Guid.Parse("cf9c3810-4b51-5e0b-a01c-582a9786a67b"),
                "Château Smith Haut Lafitte", "Château Smith Haut Lafitte", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2016, 1, "B7"),
            (Guid.Parse("313c5958-393d-5e04-ba6d-5b57fa5e5da6"),
                "Château La Fleur de Gay", "Château La Fleur de Gay", "Pomerol", "France",
                Color.Red, "Merlot", 2019, 1, "C8"),
            (Guid.Parse("6a88eebe-2b56-5539-9bde-0a9709c3dca2"),
                "Château de Sales", "Château de Sales", "Pomerol", "France",
                Color.Red, "Merlot, Cabernet Sauvignon, Cabernet Franc", 2020, 2, "D1"),
            (Guid.Parse("60b44340-ed11-5d14-81de-2885a3ea64ab"),
                "Pétrus", "Pétrus", "Pomerol", "France",
                Color.Red, "Merlot", 2016, 1, "E2"),
            (Guid.Parse("1e385599-75e1-5a11-a26f-e41835403097"),
                "Château Trotanoy", "Château Trotanoy", "Pomerol", "France",
                Color.Red, "Merlot, Cabernet Franc", 2017, 1, "A3"),
            (Guid.Parse("0991497a-fbbb-52b6-95bf-6f0fac3f112e"),
                "Château Larcis Ducasse", "Château Larcis Ducasse", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc", 2017, 1, "B4"),
            (Guid.Parse("7b6c8b45-050d-5b1a-9836-9624e8385fb9"),
                "Château Troplong Mondot", "Château Troplong Mondot", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc, Cabernet Sauvignon", 2019, 1, "C5"),
            (Guid.Parse("34abaf93-16ba-52c5-9643-147f1bc74053"),
                "Château Figeac", "Château Figeac", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Cabernet Sauvignon, Cabernet Franc, Merlot", 2021, 1, "D6"),
            (Guid.Parse("0baadfb6-c297-5d75-8b95-b1992416a107"),
                "Château Pavie", "Château Pavie", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc, Cabernet Sauvignon", 2020, 1, "E7"),
            (Guid.Parse("e56105f1-3d8d-5f05-acee-40f2e8de739e"),
                "Les Pagodes de Cos", "Château Cos d'Estournel", "Saint-Estèphe", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2015, 2, "A8"),
            (Guid.Parse("44f1b017-23ef-57db-ac6a-2f83c49438da"),
                "Château Cos d'Estournel", "Château Cos d'Estournel", "Saint-Estèphe", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2016, 1, "B1"),
            (Guid.Parse("6de1cb1e-f2f1-59d9-8cc8-da9b58508992"),
                "Château Montrose", "Château Montrose", "Saint-Estèphe", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2022, 1, "C2"),
            (Guid.Parse("85f46026-4d4b-51bd-9ec5-b6d396cafae8"),
                "Château Calon-Ségur", "Château Calon-Ségur", "Saint-Estèphe", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2018, 1, "D3"),
            (Guid.Parse("55cbb79e-9d1c-5c59-8cb8-85c3b3deab49"),
                "Château Latour", "Château Latour", "Pauillac", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc", 2019, 1, "E4"),
            (Guid.Parse("b5808bcf-1a67-58c9-95f4-0c4805058abd"),
                "Château Lynch-Bages", "Château Lynch-Bages", "Pauillac", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2014, 1, "A5"),
            (Guid.Parse("a40de217-a683-56d6-b377-532cddec5067"),
                "Château Pontet-Canet", "Château Pontet-Canet", "Pauillac", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2020, 1, "B6"),
            (Guid.Parse("46871f59-b9c3-51a4-9f96-73bf5c612ba6"),
                "Château Giscours", "Château Giscours", "Margaux", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2020, 2, "C7"),
            (Guid.Parse("21a0ac73-810f-5f87-b417-b9e93f5d875e"),
                "Château Palmer", "Château Palmer", "Margaux", "France",
                Color.Red, "Merlot, Cabernet Sauvignon, Petit Verdot", 2020, 1, "D8"),
            (Guid.Parse("e3fe6b21-5311-5105-b344-b76abcc159d2"),
                "Château Citran", "Château Citran", "Haut-Médoc", "France",
                Color.Red, "Cabernet Sauvignon, Merlot", 2014, 2, "E1"),
            (Guid.Parse("186603e0-1a2d-5fe1-b653-3ea1a547ea80"),
                "Château Léoville Las Cases", "Château Léoville Las Cases", "Saint-Julien", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc", 2014, 1, "A2"),
            (Guid.Parse("f24f3451-fc71-5669-ad8c-981ccdaeeced"),
                "Château Ducru-Beaucaillou", "Château Ducru-Beaucaillou", "Saint-Julien", "France",
                Color.Red, "Cabernet Sauvignon, Merlot", 2014, 1, "B3"),
            (Guid.Parse("cb5285f0-1e9c-566c-ac1a-77546ee47d1d"),
                "Clos des Lunes Lune d'Argent", "Clos des Lunes", "Bordeaux", "France",
                Color.White, "Sémillon, Sauvignon Blanc", 2023, 2, "C4"),
            (Guid.Parse("db1474df-ee06-5946-a899-34df985aeeae"),
                "Château Coutet", "Château Coutet", "Barsac", "France",
                Color.White, "Sémillon, Sauvignon Blanc, Muscadelle", 2021, 1, "D5"),
            (Guid.Parse("af0e66da-1970-5aec-b897-6ca98a5257c8"),
                "Château d'Yquem", "Château d'Yquem", "Sauternes", "France",
                Color.White, "Sémillon, Sauvignon Blanc", 2023, 1, "E6"),
            (Guid.Parse("300e456a-09f5-52e6-bc31-058ef4df3bd5"),
                "Château Cheval Blanc", "Château Cheval Blanc", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc", 2022, 1, "A7"),
            (Guid.Parse("734858d6-0cd1-5cc7-bfb9-a2bcf59741a4"),
                "Château Angélus", "Château Angélus", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc", 2019, 1, "B8"),
            (Guid.Parse("05eca599-d750-5795-b66e-f9a5d755e03a"),
                "Château Léoville Barton", "Château Léoville Barton", "Saint-Julien", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc", 2021, 1, "C1"),
            (Guid.Parse("e9654198-1e54-5767-a090-da37b64946e7"),
                "Château Beychevelle", "Château Beychevelle", "Saint-Julien", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2020, 2, "D2"),
            (Guid.Parse("33b5d0e9-473c-5d7e-bf1f-d6d35c2b9bea"),
                "Château Pichon Baron", "Château Pichon Baron", "Pauillac", "France",
                Color.Red, "Cabernet Sauvignon, Merlot", 2017, 1, "E3"),
            (Guid.Parse("ec2ea9d5-64e7-54bd-b70b-a0d86ead4676"),
                "Château Branaire-Ducru", "Château Branaire-Ducru", "Saint-Julien", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2015, 2, "A4"),
            (Guid.Parse("5c87471b-db5e-5c03-bcf2-45adefd1a913"),
                "Château Suduiraut", "Château Suduiraut", "Sauternes", "France",
                Color.White, "Sémillon, Sauvignon Blanc", 2021, 1, "B5"),
            (Guid.Parse("53768989-b287-5672-833f-012f28bf0357"),
                "Château Climens", "Château Climens", "Barsac", "France",
                Color.White, "Sémillon", 2023, 1, "C6"),
            (Guid.Parse("0d0489df-05ba-54da-a720-47f24a94a461"),
                "Château Carbonnieux", "Château Carbonnieux", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec", 2019, 2, "D7"),
            (Guid.Parse("0c354dc9-c3f4-587e-ba5d-cfe847c2fbfd"),
                "Château Malartic-Lagravière", "Château Malartic-Lagravière", "Pessac-Léognan", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2021, 1, "E8"),
            (Guid.Parse("7e57d0e2-39f9-52b1-b7ec-49a1bb9b0374"),
                "Domaine de Chevalier Blanc", "Domaine de Chevalier", "Pessac-Léognan", "France",
                Color.White, "Sauvignon Blanc, Sémillon", 2023, 1, "A1"),
            (Guid.Parse("ca97b6a8-2608-52db-8e26-6ba77c642884"),
                "Le Pin", "Le Pin", "Pomerol", "France",
                Color.Red, "Merlot", 2020, 1, "B2"),
            (Guid.Parse("4589c025-5322-5c85-9b52-1cd1672dcf02"),
                "Château La Conseillante", "Château La Conseillante", "Pomerol", "France",
                Color.Red, "Merlot, Cabernet Franc", 2022, 1, "C3"),
            (Guid.Parse("a61c8822-ab68-5987-9fc5-2e9d65638d64"),
                "Château Clinet", "Château Clinet", "Pomerol", "France",
                Color.Red, "Merlot, Cabernet Sauvignon, Cabernet Franc", 2019, 1, "D4"),
            (Guid.Parse("fb820e77-6154-52e1-8c08-2a3fe4c71fda"),
                "Château Lagrange (Pomerol)", "Château Lagrange", "Pomerol", "France",
                Color.Red, "Merlot, Cabernet Franc", 2018, 2, "E5"),
            (Guid.Parse("4d18a3f6-da95-5196-888c-acdb68cd3d06"),
                "Château Canon", "Château Canon", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc", 2019, 1, "A6"),
            (Guid.Parse("d566b70a-2bf5-552b-b3bc-edf0c14561cb"),
                "Clos Fourtet", "Clos Fourtet", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Sauvignon, Cabernet Franc", 2018, 1, "B7"),
            (Guid.Parse("2fdf68f0-da75-566d-a4f9-37e5e47bfd6a"),
                "Château Canon-la-Gaffelière", "Château Canon-la-Gaffelière", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc, Cabernet Sauvignon", 2020, 1, "C8"),
            (Guid.Parse("06a05d08-f9f0-5b59-aaf2-2278b193e5e8"),
                "Château Valandraud", "Château Valandraud", "Saint-Émilion Grand Cru", "France",
                Color.Red, "Merlot, Cabernet Franc, Cabernet Sauvignon", 2020, 1, "D1"),
            (Guid.Parse("63ebdce2-98ac-555b-949b-1177b5c9d983"),
                "Château Lafite Rothschild", "Château Lafite Rothschild", "Pauillac", "France",
                Color.Red, "Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot", 2021, 1, "E2"),
            (Guid.Parse("a0bb2c59-3e38-5ed6-8dfa-4b20827d3f15"),
                "Petite Arvine", "Cave du Rhodan", "Valais", "Suisse",
                Color.White, "Petite Arvine", 2022, 1, "F1"),
            (Guid.Parse("b0969921-9458-5f4c-9f93-598a28277369"),
                "Minuty", "Minuty", "Côtes de Provence", "France",
                Color.Rose, "Grenache, Cinsault, Syrah, Tibouren", 2023, 2, "F2"),
            (Guid.Parse("f7bbd882-78bf-5a16-8f79-f1e0161a3a24"),
                "Champagne Brut", "Maison Réserve", "Champagne", "France",
                Color.Sparkling, "Chardonnay, Pinot Noir, Pinot Meunier", 2018, 1, "F3"),
        };

        var list = new List<Bottle>(specs.Length);
        foreach (var s in specs)
        {
            var bottle = new Bottle
            {
                Id = s.Id,
                Name = s.Name,
                Producer = s.Producer,
                Region = s.Region,
                Country = s.Country,
                Color = s.Color,
                Varietal = s.Varietal,
                Vintage = s.Vintage,
                Quantity = s.Quantity,
                PriceChf = null,
                PurchaseDate = null,
                Bin = s.Bin,
                Status = BottleStatus.InStock,
                Notes = null,
                CreatedAt = SeedTimestamp,
                UpdatedAt = SeedTimestamp
            };
            MaturityRules.ApplyReadyToDrink(bottle, asOfYear);
            bottle.UpdatedAt = SeedTimestamp;
            list.Add(bottle);
        }

        return list;
    }
}
